PUT http://localhost:4000/customers/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe updated",
  "email": "test23@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09"
}
###